/**
 * Ticket status lifecycle:
 *   idea → requirement-review → pending-approval → pending-implementation → implementing → review-uat → done
 *
 * Terminal statuses: done, rejected, cancelled
 * Parking status:   on-hold (can resume to any active status)
 */
export type TicketStatus =
  | "idea"
  | "requirement-review"
  | "pending-approval"
  | "pending-implementation"
  | "implementing"
  | "review-uat"
  | "done"
  | "rejected"
  | "on-hold"
  | "cancelled";

/** Terminal statuses — tickets here are considered resolved */
export const TERMINAL_STATUSES: TicketStatus[] = ["done", "rejected", "cancelled"];

/** Active statuses — tickets currently in the pipeline (not parked or terminal) */
export const ACTIVE_STATUSES: TicketStatus[] = [
  "idea",
  "requirement-review",
  "pending-approval",
  "pending-implementation",
  "implementing",
  "review-uat",
];

export type TicketPriority = "critical" | "high" | "medium" | "low";

export type TicketType =
  | "feature"
  | "bug"
  | "task"
  | "review-request"
  | "work-report"
  | "fyi"
  | "idea"
  | "question";

/** Effort estimate sizes */
export type Estimate = "XS" | "S" | "M" | "L" | "XL";

export interface Comment {
  id: string;
  author: string;
  content: string;
  timestamp: string;
  editedAt?: string;
}

/** One entry in the JSONL audit log — records every mutation */
export interface AuditEntry {
  ticket_id: string;
  action: "created" | "updated" | "commented" | "attached" | "comment_edited" | "comment_deleted";
  actor: string;
  timestamp: string;
  /** Map of field name → [old_value, new_value] */
  changes: Record<string, [unknown, unknown]>;
}

/** Core ticket model — stored as flat JSON files in ~/Documents/ai-usage/tickets/ */
export interface Ticket {
  id: string;
  project: string;
  title: string;
  summary: string;
  description: string;
  status: TicketStatus;
  priority: TicketPriority;
  type: TicketType;
  assignee: string;
  estimate: Estimate;
  from: string;
  to: string;
  tags: string[];
  dependencies: string[];
  doc_ref: string;
  attachments: string[];
  comments: Comment[];
  createdAt: string;
  updatedAt: string;
  resolvedAt: string | null;
}

/** Input for creating a new ticket — id and timestamps are generated by TicketStore */
export type CreateTicketInput = Omit<Ticket, "id" | "createdAt" | "updatedAt" | "resolvedAt"> & {
  resolvedAt?: string | null;
};

/** Fields that can be updated after creation */
export type UpdateTicketInput = Partial<
  Omit<Ticket, "id" | "project" | "createdAt">
>;

/** counter.json structure — one entry per project prefix */
export type CounterStore = Record<string, number>;
