/**
 * Ticket status lifecycle:
 *   idea → requirement-review → pending-approval → pending-implementation → implementing → review-uat → done
 *
 * Terminal statuses: done, rejected, cancelled
 * Deprioritized: use the `backlog` tag (not a status)
 * Blocked: use the `blocked` tag + blockedBy field
 */
export type TicketStatus =
  | "idea"
  | "requirement-review"
  | "pending-approval"
  | "pending-implementation"
  | "implementing"
  | "review-uat"
  | "done"
  | "rejected"
  | "cancelled";

/** Terminal statuses — tickets here are considered resolved */
export const TERMINAL_STATUSES: TicketStatus[] = ["done", "rejected", "cancelled"];

/** Active statuses — tickets currently in the pipeline (not parked or terminal) */
export const ACTIVE_STATUSES: TicketStatus[] = [
  "idea",
  "requirement-review",
  "pending-approval",
  "pending-implementation",
  "implementing",
  "review-uat",
];

export type TicketPriority = "critical" | "high" | "medium" | "low";

export type TicketType =
  | "feature"
  | "bug"
  | "task"
  | "review-request"
  | "work-report"
  | "fyi"
  | "idea"
  | "question";

/** Effort estimate sizes */
export type Estimate = "XS" | "S" | "M" | "L" | "XL";

/** Sub-ticket status lifecycle: open → in-progress → done */
export type SubTicketStatus = "open" | "in-progress" | "done";

/** A git branch linked to a ticket */
export interface LinkedBranch {
  repo: string;
  branch: string;
  sha: string;
  linkedAt: string;
  linkedBy: string;
}

/** A git commit linked to a ticket */
export interface LinkedCommit {
  repo: string;
  sha: string;
  message: string;
  author: string;
  timestamp: string;
  linkedAt: string;
  linkedBy: string;
}

/** Embedded sub-ticket — lives inside parent ticket, not on the board */
export interface SubTicket {
  id: string;           // e.g., "PA-042-ST-1"
  title: string;
  summary: string;
  status: SubTicketStatus;
  assignee: string;
  priority: TicketPriority;
  estimate: Estimate;
  createdAt: string;
  updatedAt: string;
}

export interface Comment {
  id: string;
  author: string;
  content: string;
  timestamp: string;
  editedAt?: string;
}

/** A typed document reference attached to a ticket */
export interface DocRef {
  /** Document type: 'requirements' | 'spike' | 'implementation' | 'review-report' | 'attachment' | 'url' */
  type: string;
  /** Relative path to the document (within ~/Documents/ai-usage/) or absolute http/https URL */
  path: string;
  /** At most one doc_ref per ticket may be primary */
  primary: boolean;
  /** ISO timestamp when this ref was added */
  addedAt: string;
  /** Agent or user who added this ref */
  addedBy: string;
}

/** One entry in the JSONL audit log — records every mutation */
export interface AuditEntry {
  ticket_id: string;
  action: "created" | "updated" | "commented" | "attached" | "comment_edited" | "comment_deleted" | "doc_ref_added" | "doc_ref_removed" | "doc_ref_updated" | "moved" | "branch_link_added" | "branch_link_removed" | "commit_link_added" | "commit_link_removed" | "deleted";
  actor: string;
  timestamp: string;
  /** Map of field name → [old_value, new_value] */
  changes: Record<string, [unknown, unknown]>;
}

/** Alias file — replaces a ticket file when it is moved to another project */
export interface AliasRecord {
  _alias: true;
  movedTo: string;
  movedAt: string;
  movedBy: string;
}

/** Core ticket model — stored as flat JSON files in ~/Documents/ai-usage/tickets/ */
export interface Ticket {
  id: string;
  project: string;
  title: string;
  summary: string;
  description: string;
  status: TicketStatus;
  priority: TicketPriority;
  type: TicketType;
  assignee: string;
  estimate: Estimate;
  from: string;
  to: string;
  tags: string[];
  blockedBy: string[];
  doc_refs: DocRef[];
  linkedBranches: LinkedBranch[];
  linkedCommits: LinkedCommit[];
  comments: Comment[];
  subTickets: SubTicket[];
  nextSubTicketCounter: number;
  createdAt: string;
  updatedAt: string;
  resolvedAt: string | null;
}

/** Input for creating a new ticket — id, timestamps, and sub-ticket fields are generated by TicketStore */
export type CreateTicketInput = Omit<Ticket, "id" | "createdAt" | "updatedAt" | "resolvedAt" | "subTickets" | "nextSubTicketCounter" | "linkedBranches" | "linkedCommits"> & {
  resolvedAt?: string | null;
  linkedBranches?: LinkedBranch[];
  linkedCommits?: LinkedCommit[];
};

/** Input for adding a single doc_ref to a ticket */
export interface AddDocRefInput {
  /** Document type (defaults to 'attachment' if omitted) */
  type?: string;
  /** Relative path to the document */
  path: string;
  /** Mark as primary doc_ref — demotes any existing primary */
  primary?: boolean;
  /** Override addedBy — defaults to actor */
  addedBy?: string;
}

/** Input for linking a branch to a ticket */
export interface AddLinkedBranchInput {
  repo: string;
  branch: string;
  sha?: string;
  linkedBy?: string;
}

/** Input for linking a commit to a ticket */
export interface AddLinkedCommitInput {
  repo: string;
  sha: string;
  message?: string;
  author?: string;
  timestamp?: string;
  linkedBy?: string;
}

/** Fields that can be updated after creation */
export type UpdateTicketInput = Partial<
  Omit<Ticket, "id" | "project" | "createdAt" | "subTickets" | "nextSubTicketCounter">
> & {
  /** Add a doc_ref to the array (additive, does not replace) */
  add_doc_ref?: AddDocRefInput;
  /** Remove a doc_ref by exact path match */
  remove_doc_ref?: string;
  /** Add a linked branch (upsert by repo:branch) */
  add_linked_branch?: AddLinkedBranchInput;
  /** Remove a linked branch by "repo:branch" key */
  remove_linked_branch?: string;
  /** Add a linked commit (upsert by sha) */
  add_linked_commit?: AddLinkedCommitInput;
  /** Remove a linked commit by sha */
  remove_linked_commit?: string;
};

/** counter.json structure — one entry per project prefix */
export type CounterStore = Record<string, number>;

// ─── Doc-ref type taxonomy (Phase 4.1, PA-1210) ─────────────────────────────────

/**
 * Canonical lowercase doc-ref type codes.
 * Use `DOC_REF_TYPE_DISPLAY` to get the uppercase display string.
 */
export const STANDARD_DOC_REF_TYPES: readonly string[] = [
  "req",
  "uat",
  "impl",
  "orch",
  "plan",
  "spike",
  "session",
  "log",
  "url",
  "attachment",
] as const;

/**
 * Map from any doc-ref type (short code or long-form alias) to its canonical
 * uppercase display form.
 * Covers all `STANDARD_DOC_REF_TYPES` plus long-form aliases.
 */
export const DOC_REF_TYPE_DISPLAY: Readonly<Record<string, string>> = {
  // Short codes → uppercase display
  req: "REQ",
  uat: "UAT",
  impl: "IMPL",
  orch: "ORCH",
  plan: "PLAN",
  spike: "SPIKE",
  session: "SESSION",
  log: "LOG",
  url: "URL",
  attachment: "ATTACHMENT",
  // Long-form aliases → uppercase display
  requirements: "REQ",
  implementation: "IMPL",
  review: "REVIEW",
  "review-report": "REVIEW",
} as const;
