/**
 * Ticket status lifecycle:
 *   idea → requirement-review → pending-approval → pending-implementation → implementing → review-uat → done
 *
 * Terminal statuses: done, rejected, cancelled
 * Deprioritized: use the `backlog` tag (not a status)
 * Blocked: use the `blocked` tag + blockedBy field
 */
export type TicketStatus =
  | "idea"
  | "requirement-review"
  | "pending-approval"
  | "pending-implementation"
  | "implementing"
  | "review-uat"
  | "done"
  | "rejected"
  | "cancelled";

/** Terminal statuses — tickets here are considered resolved */
export const TERMINAL_STATUSES: TicketStatus[] = ["done", "rejected", "cancelled"];

/** Active statuses — tickets currently in the pipeline (not parked or terminal) */
export const ACTIVE_STATUSES: TicketStatus[] = [
  "idea",
  "requirement-review",
  "pending-approval",
  "pending-implementation",
  "implementing",
  "review-uat",
];

export type TicketPriority = "critical" | "high" | "medium" | "low";

export type TicketType =
  | "feature"
  | "bug"
  | "task"
  | "review-request"
  | "work-report"
  | "fyi"
  | "idea"
  | "question";

/** Effort estimate sizes */
export type Estimate = "XS" | "S" | "M" | "L" | "XL";

export interface Comment {
  id: string;
  author: string;
  content: string;
  timestamp: string;
  editedAt?: string;
}

/** A typed document reference attached to a ticket */
export interface DocRef {
  /** Document type: 'requirements' | 'spike' | 'implementation' | 'review-report' | 'attachment' */
  type: string;
  /** Relative path to the document (within ~/Documents/ai-usage/) */
  path: string;
  /** At most one doc_ref per ticket may be primary */
  primary: boolean;
  /** ISO timestamp when this ref was added */
  addedAt: string;
  /** Agent or user who added this ref */
  addedBy: string;
}

/** One entry in the JSONL audit log — records every mutation */
export interface AuditEntry {
  ticket_id: string;
  action: "created" | "updated" | "commented" | "attached" | "comment_edited" | "comment_deleted" | "doc_ref_added" | "doc_ref_removed" | "doc_ref_updated" | "moved";
  actor: string;
  timestamp: string;
  /** Map of field name → [old_value, new_value] */
  changes: Record<string, [unknown, unknown]>;
}

/** Alias file — replaces a ticket file when it is moved to another project */
export interface AliasRecord {
  _alias: true;
  movedTo: string;
  movedAt: string;
  movedBy: string;
}

/** Core ticket model — stored as flat JSON files in ~/Documents/ai-usage/tickets/ */
export interface Ticket {
  id: string;
  project: string;
  title: string;
  summary: string;
  description: string;
  status: TicketStatus;
  priority: TicketPriority;
  type: TicketType;
  assignee: string;
  estimate: Estimate;
  from: string;
  to: string;
  tags: string[];
  blockedBy: string[];
  doc_refs: DocRef[];
  comments: Comment[];
  createdAt: string;
  updatedAt: string;
  resolvedAt: string | null;
}

/** Input for creating a new ticket — id and timestamps are generated by TicketStore */
export type CreateTicketInput = Omit<Ticket, "id" | "createdAt" | "updatedAt" | "resolvedAt"> & {
  resolvedAt?: string | null;
};

/** Input for adding a single doc_ref to a ticket */
export interface AddDocRefInput {
  /** Document type (defaults to 'attachment' if omitted) */
  type?: string;
  /** Relative path to the document */
  path: string;
  /** Mark as primary doc_ref — demotes any existing primary */
  primary?: boolean;
  /** Override addedBy — defaults to actor */
  addedBy?: string;
}

/** Fields that can be updated after creation */
export type UpdateTicketInput = Partial<
  Omit<Ticket, "id" | "project" | "createdAt">
> & {
  /** Add a doc_ref to the array (additive, does not replace) */
  add_doc_ref?: AddDocRefInput;
  /** Remove a doc_ref by exact path match */
  remove_doc_ref?: string;
};

/** counter.json structure — one entry per project prefix */
export type CounterStore = Record<string, number>;
